# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Database
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.user=
spring.liquibase.password=

# Spring security
spring.security.user.name=
spring.security.user.password=

# Security
spring.web.error.whitelabel.enabled=false
spring.web.error.include-stacktrace=never
spring.web.error.include-path=never
